"""Разговоры: episodes, turns, dialog_memory.

Таблицы этапа 2 — эпизод, ходы внутри него и профиль диалога. Расписание
(`scheduled_events`) сюда не входит: на этом этапе эпизод начинается по
команде `/next`, а не по будильнику, и заводить таблицу под код, которого
ещё нет, значит гадать о её форме заранее.

Revision ID: 0004
Revises: 0003
Create Date: 2026-09-09 22:12:35.768818
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0004"
down_revision: str | None = "0003"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "dialog_memory",
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "profile", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column("tokens_estimate", sa.SmallInteger(), server_default="0", nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_dialog_memory_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("user_id", name=op.f("pk_dialog_memory")),
    )
    op.create_table(
        "episodes",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("pack_id", sa.BigInteger(), nullable=True),
        sa.Column("intent", sa.String(length=2), nullable=False),
        sa.Column("scene", sa.String(length=160), nullable=True),
        sa.Column(
            "frame", postgresql.JSONB(astext_type=sa.Text()), server_default="{}", nullable=False
        ),
        sa.Column("opening_text", sa.Text(), nullable=True),
        sa.Column("target_word_ids", postgresql.ARRAY(sa.BigInteger()), nullable=False),
        sa.Column("status", sa.String(length=16), server_default="pending", nullable=False),
        sa.Column("turns_count", sa.SmallInteger(), server_default="0", nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("opened_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("summary_ru", sa.Text(), nullable=True),
        sa.Column(
            "cost_usd", sa.Numeric(precision=10, scale=6), server_default="0", nullable=False
        ),
        sa.CheckConstraint(
            "intent IN ('D1', 'D2', 'D3', 'D4', 'D5')", name=op.f("ck_episodes_intent_known")
        ),
        sa.CheckConstraint(
            "status IN ('pending', 'open', 'closed', 'abandoned')",
            name=op.f("ck_episodes_episode_status_known"),
        ),
        sa.CheckConstraint(
            "array_length(target_word_ids, 1) BETWEEN 1 AND 3",
            name=op.f("ck_episodes_target_word_ids_size"),
        ),
        sa.CheckConstraint(
            "turns_count BETWEEN 0 AND 4", name=op.f("ck_episodes_turns_count_range")
        ),
        sa.ForeignKeyConstraint(
            ["pack_id"], ["packs.id"], name=op.f("fk_episodes_pack_id_packs"), ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_episodes_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_episodes")),
    )
    op.create_index("ix_episodes_user_id_status", "episodes", ["user_id", "status"], unique=False)
    op.create_table(
        "turns",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("episode_id", sa.BigInteger(), nullable=False),
        sa.Column("idx", sa.SmallInteger(), nullable=False),
        sa.Column("bot_text", sa.Text(), nullable=False),
        sa.Column("user_text", sa.Text(), nullable=True),
        sa.Column(
            "assessments",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="[]",
            nullable=False,
        ),
        sa.Column(
            "corrections",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="[]",
            nullable=False,
        ),
        sa.Column(
            "sent_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("answered_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("latency_ms", sa.Integer(), nullable=True),
        sa.Column(
            "cost_usd", sa.Numeric(precision=10, scale=6), server_default="0", nullable=False
        ),
        sa.CheckConstraint("idx >= 0", name=op.f("ck_turns_turn_idx_non_negative")),
        sa.ForeignKeyConstraint(
            ["episode_id"],
            ["episodes.id"],
            name=op.f("fk_turns_episode_id_episodes"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_turns")),
        sa.UniqueConstraint("episode_id", "idx", name="uq_turns_episode_id_idx"),
    )
    op.create_index(op.f("ix_turns_episode_id"), "turns", ["episode_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_turns_episode_id"), table_name="turns")
    op.drop_table("turns")
    op.drop_index("ix_episodes_user_id_status", table_name="episodes")
    op.drop_table("episodes")
    op.drop_table("dialog_memory")
    # ### end Alembic commands ###
